#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
source ~/.zprezto/init.zsh

alias think="cd ~/Code/thinkCERCA"
alias postgres="open -a Postgres"
alias sunspot="rake sunspot:solr:start"

alias gbl="git branch --list"
